name: Build Docker image and push to DockerHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Build Docker image and push to DockerHub"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lucaprete/laravel-on-docker
        tag_with_ref: true
        tag_with_sha: true
        tags: latest
